// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzQAfj9GeSKG8bAMVQJlPOY0HgQNB-Xwc',
    appId: '1:733996798765:web:5ea52fcee28014dc4479a4',
    messagingSenderId: '733996798765',
    projectId: 'flutterisaretdilitercumani',
    authDomain: 'flutterisaretdilitercumani.firebaseapp.com',
    storageBucket: 'flutterisaretdilitercumani.appspot.com',
    measurementId: 'G-WG653S3Q66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQl0SI56VKF-7SloF2HAfuxD_GSEkZlxo',
    appId: '1:733996798765:android:8fc7f9c2aee4da3a4479a4',
    messagingSenderId: '733996798765',
    projectId: 'flutterisaretdilitercumani',
    storageBucket: 'flutterisaretdilitercumani.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfNKTcrVtbVYNand_Mw48Yh14B7nem6eo',
    appId: '1:733996798765:ios:b6ef31b49f0a9dcf4479a4',
    messagingSenderId: '733996798765',
    projectId: 'flutterisaretdilitercumani',
    storageBucket: 'flutterisaretdilitercumani.appspot.com',
    iosBundleId: 'com.example.isaretdilitercumaniprojesi',
  );
}
